### ISSUE TITLE
Cannot find module 'chai'

### ISSUE THREAD

**Issue by franciov** [kenzanlabs/pipeline-test-node#19]
I open this issue after [a jenkins task](http://build.oneplatform.build/job/CI-webui-pipeline-serve/1/console) failed with this error:

```
[17:09:44] Error in plugin 'gulp-mocha'
Message:
    Cannot find module 'chai'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/lib/jenkins/workspace/CI-webui-pipeline-serve/specs/index.spec.js:9:128)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions.(anonymous function) [as .js] (/var/lib/jenkins/workspace/CI-webui-pipeline-serve/node_modules/pipeline-test-node/node_modules/gulp-istanbul/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Node v4.4.0
Npm 2.14.20

I worked around this adding `chai` as a npm dependency explicitly in the hosting project.

**Comment by obuckley-kenzan** [comment]
@franciov 
I think my understanding is that mocha is specifically a plugin based framework, right?  Should we consider packaging our pipeline here with some useful helpers out of the box?  And if so, which ones do we pick and which ones do leave up to the consumer to install on their own?

@paul-barry-kenzan 
Thoughts?

**Comment by paul-barry-kenzan** [comment]
You bring up a good point, Mocha is suppose to be flexible. We could potentially give the option to choose any assertion engine, although, what benefit would our pipeline bring at that point, if the user has to manually install their desired setup. We agreed that we'd be opinionated to an extent, and I feel comfortable saying that Mocha, Chai, & Sinon are a solid combo that is a sure knock out! ;) Seriously though, it's a common enough "package" that defaulting to it would be best, with letting other swap things out as options could work.

**Comment by obuckley-kenzan** [comment]
I am onboard with providing the following out of the box

1. mocha
2. chia
3. sinon

**Comment by obuckley-kenzan** [comment]
However... this requires users to have npm >= 3.x right?  Because without that, these modules will install _under_ our pipeline module, not flat.

cc: @franciov / @paul-barry-kenzan

**Comment by franciov** [comment]
@obuckley-kenzan Ha, right, that explains why I had to include explicitly `chai`, and also `gulp-mocha` it seems, using npm 2.14.20 (in jenkins).

**Comment by obuckley-kenzan** [comment]
@bsawyer 
Please review

**Comment by bsawyer** [comment]
@obuckley-kenzan @paul-barry-kenzan If I understand correctly the build failed because a spec test failed to evaluate because it required chai that wasn't installed as a dependency in webui-pipeline-serve? At the very least we should move the assertion library definition for this pipeline to devDependencies. If we want to be opinionated about what the developer uses as an assertion lib it's a perfect case for a peerDependency.

**Comment by obuckley-kenzan** [comment]
@bsawyer 
I see your thoughts, and yes, in essence we are trying to be opinionated for our company use cases.  That said, if we require NPM 3, and make these libraries `dependencies` we won't need to make it a `peerDepenency`, yes?

Just seeing Mocha 3 and NPM3 as breaking changes and possibly as being done together to upgrade both at once.
